apiVersion: v2
name: lagoon-build-deploy
description:
  A Helm chart for Kubernetes which installs Lagoon remote controllers which are used for handling build and task pods
  (https://github.com/uselagoon/remote-controller).
home: https://github.com/uselagoon/lagoon-charts
icon: https://raw.githubusercontent.com/uselagoon/lagoon-charts/main/icon.png
maintainers:
- name: shreddedbacon
  email: ben.jackson@amazee.io
  url: https://amazee.io
- name: smlx
  email: scott.leggett@amazee.io
  url: https://amazee.io
kubeVersion: ">= 1.25.0-0"

type: application

version: 0.30.1

appVersion: v0.20.1

annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: republish with updated artifacthub crds
    - kind: changed
      description: update controller to v0.20.1
    - kind: added
      description: add new lagoonbuild and lagoontask v1beta2 crd versions
    - kind: changed
      description: deprecate lagoonbuild and lagoontask v1beta1 crd versions
  artifacthub.io/crds: |
    - kind: LagoonBuild
      version: v1beta2
      name: lagoonbuild
      displayName: LagoonBuild
      description: This is the CRD used for managing LagoonBuilds
    - kind: LagoonTask
      version: v1beta2
      name: lagoontask
      displayName: LagoonTask
      description: This is the CRD used for managing LagoonTasks
    - kind: LagoonBuild
      version: v1beta1
      name: lagoonbuild
      displayName: LagoonBuild
      description: Deprecated - Use the newer v1beta2 resource
    - kind: LagoonTask
      version: v1beta1
      name: lagoontask
      displayName: LagoonTask
      description: Deprecated - Use the newer v1beta2 resource
