apiVersion: v2
name: lagoon-remote
description: A Helm chart to run a lagoon-remote
home: https://github.com/uselagoon/lagoon-charts
icon: https://raw.githubusercontent.com/uselagoon/lagoon-charts/main/icon.png
maintainers:
- name: schnitzel
  email: michael@amazee.com
  url: https://amazee.io
- name: smlx
  email: scott.leggett@amazee.io
  url: https://amazee.io
kubeVersion: ">= 1.23.0-0"

# Application charts are a collection of templates that can be packaged into
# versioned archives to be deployed.
type: application

# This is the chart version. This version number should be incremented each
# time you make changes to the chart and its templates, including the app
# version.
version: 0.89.0

dependencies:
- name: lagoon-build-deploy
  version: ~0.26.0
  repository: https://uselagoon.github.io/lagoon-charts/
  condition: lagoon-build-deploy.enabled
- name: dbaas-operator
  version: ~0.3.0
  repository: https://amazeeio.github.io/charts/
  condition: dbaas-operator.enabled
- name: nats
  version: ~0.19.0
  repository: https://nats-io.github.io/k8s/helm/charts/
  condition: nats.enabled

# This section is used to collect a changelog for artifacthub.io
# It should be started afresh for each release
# Valid supported kinds are added, changed, deprecated, removed, fixed and security
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: bump ssh-portal from v0.34.0 to version v0.36.0
      links:
        - name: ssh-portal releases
          url: https://github.com/uselagoon/lagoon-ssh-portal/releases
    - kind: changed
      description: bump insights-remote from v0.0.9 to version v0.0.10
      links:
        - name: ssh-portal releases
          url: https://github.com/uselagoon/insights-remote/releases/tag/v0.0.10
    - kind: changed
      description: bump remote-calculator from v0.5.3 to version v0.6.0
      links:
        - name: ssh-portal releases
          url: https://github.com/uselagoon/storage-calculator/releases/tag/v0.6.0
