{{- if .Values.insightsTrivy.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lagoon-core.insightsTrivy.fullname" . }}
  labels:
    {{- include "lagoon-core.insightsTrivy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lagoon-core.insightsTrivy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
    {{- with .Values.insightsTrivy.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "lagoon-core.insightsTrivy.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml (coalesce .Values.insightsTrivy.podSecurityContext .Values.podSecurityContext) | nindent 8 }}
      containers:
      - name: insights-trivy
        securityContext:
          {{- toYaml .Values.insightsTrivy.securityContext | nindent 10 }}
        image: "{{ .Values.insightsTrivy.image.repository }}:{{ coalesce .Values.insightsTrivy.image.tag .Values.imageTag .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.insightsTrivy.image.pullPolicy }}
        resources:
          {{- toYaml .Values.insightsTrivy.resources | nindent 10 }}
        command: ["trivy", "server", "--cache-dir=/tmp", "--listen=0.0.0.0:4954", "-d"]
        ports:
            - containerPort: 4954
              protocol: TCP
              name: tcp-4954
        livenessProbe:
            httpGet:
              path: /healthz
              port: 4954
        readinessProbe:
            httpGet:
              path: /healthz
              port: 4954
      {{- with .Values.insightsTrivy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ include "lagoon-core.name" . }}
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - {{ include "lagoon-core.insightsTrivy.fullname" . }}
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
      {{- with .Values.insightsTrivy.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.insightsTrivy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}