apiVersion: v1
kind: Service
metadata:
  name: docker-host
  labels:
    dockerhost.lagoon.sh/dedicated: "false"
    {{- include "lagoon-remote.dockerHost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dockerHost.service.type }}
  ports:
    - port: {{ .Values.dockerHost.service.port }}
      targetPort: docker-daemon
      protocol: TCP
      name: docker-daemon
  selector:
    {{- include "lagoon-remote.dockerHost.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 14400 # 4 hours
{{- $name := include "lagoon-remote.dockerHost.fullname" . -}}
{{- $labels := include "lagoon-remote.dockerHost.labels" .  -}}
{{- $stype := .Values.dockerHost.service.type -}}
{{- $sport := .Values.dockerHost.service.port -}}
{{- $replicaCount := .Values.dockerHost.replicaCount | int -}}
{{- range $index0 := until $replicaCount -}}
{{- $index1 := $index0 | add1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: docker-host-{{ $index0 }}
  labels:
    dockerhost.lagoon.sh/dedicated: "true"
{{ $labels | indent 4 }}
spec:
  type: {{ $stype }}
  ports:
    - port: {{ $sport }}
      targetPort: docker-daemon
      protocol: TCP
      name: docker-daemon
  sessionAffinity: ClientIP
  selector:
    statefulset.kubernetes.io/pod-name: {{ $name }}-{{ $index0 }}
{{- end }}
