{{- if .Values.sysctlConfigure.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "lagoon-remote.sysctlConfigure.fullname" . }}
  labels:
    {{- include "lagoon-remote.sysctlConfigure.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "lagoon-remote.sysctlConfigure.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "lagoon-remote.sysctlConfigure.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}