{{- if .Values.sysctlConfigure.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lagoon-remote.sysctlConfigure.serviceAccountName" . }}
  labels:
    {{- include "lagoon-remote.sysctlConfigure.labels" . | nindent 4 }}
{{- end }}