{{- if .Values.sysctlConfigure.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "lagoon-remote.sysctlConfigure.fullname" . }}
  labels:
    {{- include "lagoon-remote.sysctlConfigure.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - patch
{{- end }}