apiVersion: v2
name: lagoon-logging
description: >
  A Helm chart for Kubernetes which installs the Lagoon container and router
  logs collection system.
home: https://github.com/amazeeio/charts
icon: https://raw.githubusercontent.com/uselagoon/lagoon-charts/main/icon.png
maintainers:
- name: smlx
  email: scott.leggett@amazee.io
  url: https://amazee.io
kubeVersion: ">= 1.23.0-0"

# Application charts are a collection of templates that can be packaged into
# versioned archives to be deployed.
type: application

# This is the chart version. This version number should be incremented each
# time you make changes to the chart and its templates, including the app
# version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.81.1

dependencies:
- name: logging-operator
  repository: https://kube-logging.github.io/helm-charts
  version: ~4.2.0
  condition: logging-operator.enabled

# This section is used to collect a changelog for artifacthub.io
# It should be started afresh for each release
# Valid supported kinds are added, changed, deprecated, removed, fixed and security
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: security
      description: >
        Previously the test role and rolebinding were being installed
        unconditionally. With this change they are only installed when running
        helm test and then removed.

        Having the role and rolebinding installed unconditionally would mean
        that any serviceaccount (including the default) would be able to view
        service objects in the lagoon-logging namespace. This is an unnecessary
        elevation of privilege, but these service objects do not contain
        anything sensitive.
