apiVersion: v2
name: lagoon-core
description: >
  A Helm chart for Kubernetes which deploys Lagoon's core components.
home: https://github.com/uselagoon/lagoon-charts
icon: https://raw.githubusercontent.com/uselagoon/lagoon-charts/main/icon.png
maintainers:
- name: smlx
  email: scott.leggett@amazee.io
  url: https://amazee.io
- name: shreddedbacon
  email: ben.jackson@amazee.io
  url: https://amazee.io
kubeVersion: ">= 1.25.0-0"

# Application charts are a collection of templates that can be packaged into
# versioned archives to be deployed.
type: application

# This is the chart version. This version number should be incremented each
# time you make changes to the chart and its templates, including the app
# version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.50.0

# This is the version number of the application being deployed. This version
# number should be incremented each time you make changes to the application.
# Versions are not expected to follow Semantic Versioning. They should reflect
# the version the application is using.
appVersion: v2.23.0

dependencies:
- name: nats
  version: ~1.2.0
  repository: https://nats-io.github.io/k8s/helm/charts/
  condition: nats.enabled

# This section is used to collect a changelog for artifacthub.io
# It should be started afresh for each release
# Valid supported kinds are added, changed, deprecated, removed, fixed and security
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: update lagoon-core appVersion to v2.23.0
      links:
        - name: Lagoon 2.23.0 release notes
          url: https://docs.lagoon.sh/releases/2.23.0
    - kind: changed
      description: add KEYCLOAK_ADMIN_API_CLIENT_SECRET variable to keycloak and api deployment
    - kind: changed
      description: update uselagoon/lagoon-ssh-portal/ssh-portal-api from v0.41.3 to v0.41.4
    - kind: changed
      description: update uselagoon/lagoon-ssh-portal/ssh-token from v0.41.3 to v0.41.4
    - kind: changed
      description: update uselagoon/lagoon-opensearch-sync from v0.8.0 to v0.8.1
    - kind: changed
      description: update NATS chart dependency to 1.2.8
