name: Release Charts

on:
  push:
    branches:
    - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: "0"

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Add dependency chart repos
      run: |
        helm repo add lagoon https://uselagoon.github.io/lagoon-charts/
        helm repo add amazeeio https://amazeeio.github.io/charts/
        helm repo add nats https://nats-io.github.io/k8s/helm/charts/
        helm repo add kube-logging https://kube-logging.github.io/helm-charts

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584 # v1.6.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        # don't upload a chart if an existing tag exists
        CR_SKIP_EXISTING: "true"
